### ISSUE TITLE
JSONParser().parse() leaks memory

### ISSUE THREAD

**Issue by donut** [Zewo/Zewo#72]
[Gist](https://gist.github.com/donut/cdfea31ab37b6e071d40b25fcb4ed203)

I haven't noticed it in all situations, but the above gist seems to reliable reproduce a ~0.3 MB leak every cycle.

``` swift
import File
import JSON

let path = try File.workingDirectory() + "/data.json"

every(10.seconds) { _ in
  do {
    let file = try File(path: path, mode: .read)
    let json = try JSONParser().parse(file.read()) // leaks ~250KB every cycle
    file.close()
    print("Whoo hoo")
  } catch {
    print("Failed parsing: \(error)")
  }
}

let infiniteCaffeine = Channel<Int>()
infiniteCaffeine.receive()
```

See the gist for the contents of data.json.

**Comment by donut** [comment]
So, letting this run for longer it seems that it's not that bad. I left it running for around 10 minutes and it only went up to 2.9 MB usage (Activity Monitor). Probably should still be looked into by someone more knowledgeable about these things than me.

**Comment by scottbyrns** [comment]
@donut I spent a couple hours trying to track down the memory leak and found that its caused by the coroutine cache. As this executes it creates more coroutines that are cached. It will stop growing in memory consumption once it hits 64 cached coroutines. I ran your example in a while true loop without the coroutines and never saw an increase in memory consumption.
